alert("добрый день ")
alert(" Здравствуйте ")
alert(" Мне бы хотелось получить у вас роботу")
let r = prompt(" как вас зовут?")
alert(" отличто  " + r)
let x = prompt(" Сколько вам лет?")
alert(" хорошо " )
let e = prompt(" Есть ли у вас образовании?")
alert(" понятно " + e)
let q = prompt(" Есть ли у вас стаж роботы в этой сфере?")
alert(" понятно " )
let t = prompt(" данные о предыдущих местах работы.?")
alert(" отлично " )
let w = prompt(" Где вы проживаете на данный момент?")
alert(" понятно " )
let d = prompt(" семейное положение и краткие сведения о близких родственниках?")
alert(" хорошо " )
let j = prompt(" контакты?")
alert(" ясно " )
let l = prompt(" адрес регистрации (прописка), а также адрес фактического проживания?")
alert(" ок " )
console.log(r)
console.log(x)
console.log(q)
console.log(w)
console.log(e)
console.log(t)
console.log(d)
console.log(j)
console.log(l)