alert("Я задам вам 12 вопросов")
let u = prompt("Укажите ваш пол?")
alert(u + ", отлично")
console.log (u)
let r = prompt("Как вас зовут?")
alert(r + ", меня зовут Ви, приятно познакомится)" )
console.log (r)
let q = prompt("Какие у вас образования?")
alert(q + ", поздравляю у вас низший уровень разума" )
console.log (q)
let w = prompt("Сколько вам лет?")
alert(w + ", поздравляем вы дед" )
console.log (w)
let y = prompt("Какой опыт програмирования?")
alert(y + ", вау вы меня возбуждаете)))" )
console.log (y)
let e = prompt("Какую зарплату хотели бы?")
alert(e + ", мы подумаем" )
console.log (e)
let t = prompt("Есть любимое хобби?")
alert(t + ", мне нравится это увлечение очень сильно" )
console.log (t)
let o = prompt("Введите свои паспортные данные?")
alert(o + ", мы это учтем")
console.log (o)
let p = prompt("Укажите свой номер?")
alert(p + ", спасибо за доверие своих данных" )
console.log (p) 
alert("Досвидание")